language: node_js
node_js:
  - 10.13
## Cache NPM folder and Cypress binary
## to avoid downloading Cypress again and again
cache:
  directories:
    - ~/.npm
    - ~/.cache
## use the new "ci" command for fastest installs on CI
install:
  - yarn install
before_script:
  ## runs the 'start' script
  ## the '-- --silent' suppresses output
  ## else our travis logs would be cluttered
  ## with output from HTTP requests
  ## https://docs.npmjs.com/cli/start
  ## ---------------------------------------
  ## we use the '&' ampersand which tells
  ## travis to run this process in the background
  ## else it would block execution and hang travis
  - npm run start --silent &
script:
  ## now run cypress headlessly
  ## and record all of the tests.
  ## Cypress will search for a
  ## CYPRESS_RECORD_KEY environment
  ## variable by default and apply
  ## this to the run.
  - npm run test
  ## alternatively we could specify
  ## a specific record key to use
  ## like this without having to
  ## configure environment variables
  ## - cypress run --record --key <your_record_key>